import { env } from "cloudflare:test";
import schema from "../migrations/0001_catalog.sql?raw";
import accounts from "../migrations/0002_accounts_grants.sql?raw";
import origin from "../migrations/0003_origin_and_views.sql?raw";
import annotations from "../migrations/0004_private_annotations.sql?raw";
import indexes from "../migrations/0005_account_catalog_indexes.sql?raw";
import limits from "../migrations/0006_storage_and_auth_limits.sql?raw";
import inference from "../migrations/0007_cloud_inference_work.sql?raw";
import albums from "../migrations/0008_shared_albums.sql?raw";
import albumFacts from "../migrations/0009_album_photo_facts.sql?raw";
import contacts from "../migrations/0010_account_contacts.sql?raw";
import peopleLinks from "../migrations/0011_account_people_links.sql?raw";
import { beforeAll } from "vitest";
beforeAll(async () => {
  await env.DB.exec(schema.replace(/\n/g, " "));
  await env.DB.exec(accounts.replace(/\n/g, " "));
  await env.DB.exec(origin.replace(/\n/g, " "));
  await env.DB.exec(annotations.replace(/\n/g, " "));
  await env.DB.exec(indexes.replace(/\n/g, " "));
  await env.DB.exec(limits.replace(/\n/g, " "));
  await env.DB.exec(inference.replace(/\n/g, " "));
  await env.DB.exec(albums.replace(/\n/g, " "));
  await env.DB.exec(albumFacts.replace(/\n/g, " "));
  await env.DB.exec(contacts.replace(/\n/g, " "));
  await env.DB.exec(peopleLinks.replace(/\n/g, " "));
});
